@Exchange
Feature: Generated sharable link

  @DEMO-10 @OPEN
  Scenario: Autogenerated web link from console
    Given a new ad in the console
    When I try to preview it
    Then it generates a unique public link to share
